export type ItemType = "component" | "playground";

export type Category =
  | "button"
  | "input"
  | "feedback"
  | "navigation"
  | "layout"
  | "text"
  | "disclosure"
  | "media"
  | "playground";

export type RegistryItem = {
  slug: string;
  title: string;
  /** One-line short description shown on gallery cards. */
  tagline?: string;
  /** Full description shown on detail pages. */
  description: string;
  date: string;
  tech: string[];
  tags: string[];
  type: ItemType;
  category: Category;
  featured?: boolean;
};

export const registry: RegistryItem[] = [
  // --- Components (reusable, importable) ---
  {
    slug: "animated-border",
    title: "Animated border",
    tagline: "Rotating conic gradient border with cursor-tinted palette.",
    description: "Card with a rotating conic gradient border. Colours shift based on cursor position via pastelColour — every spot on screen produces a unique palette.",
    date: "2026-03-10",
    tech: ["Spring Physics", "Conic Gradient", "requestAnimationFrame"],
    tags: ["border", "gradient", "conic", "card", "cursor"],
    type: "component",
    category: "layout",
  },
  {
    slug: "magnetic-button",
    title: "Magnetic button",
    tagline: "Stretches toward your cursor, bounces on click.",
    description: "Button that stretches toward your cursor with spring physics. Glows with position-mapped pastel colour on proximity. Click for a satisfying bounce.",
    date: "2026-03-06",
    tech: ["Spring Physics", "DOM Transforms", "Pointer Events"],
    tags: ["button", "magnetic", "spring", "interaction"],
    type: "component",
    category: "button",
  },
  {
    slug: "spotlight-card",
    title: "Spotlight card",
    tagline: "Cursor-reactive pastel border glow.",
    description: "Card with a cursor-reactive pastel border glow. Border colour shifts based on where the cursor sits within the card.",
    date: "2026-03-06",
    tech: ["CSS Border", "Pointer Events", "requestAnimationFrame"],
    tags: ["card", "spotlight", "border", "glow"],
    type: "component",
    category: "layout",
  },
  {
    slug: "glow-checkbox",
    title: "Glow checkbox",
    tagline: "Spring-overshoot checkmark with pastel bloom.",
    description: "Checkbox with a spring-physics checkmark that overshoots on toggle. Border glows with cursor-mapped pastel colour on proximity. Box fills with pastel when checked, with a subtle outer bloom.",
    date: "2026-03-15",
    tech: ["Spring Physics", "requestAnimationFrame", "pastelColour"],
    tags: ["checkbox", "form", "spring", "glow", "cursor"],
    type: "component",
    category: "input",
  },
  {
    slug: "glow-select",
    title: "Glow select",
    tagline: "Floating-label dropdown with spring chevron.",
    description: "Dropdown select with a floating label that springs on selection and a cursor-mapped pastel border glow. Dropdown springs in with opacity and translateY. Chevron rotates with spring physics.",
    date: "2026-03-15",
    tech: ["Spring Physics", "requestAnimationFrame", "pastelColour"],
    tags: ["select", "dropdown", "form", "floating-label", "glow", "spring", "cursor"],
    type: "component",
    category: "input",
    featured: true,
  },
  {
    slug: "glow-input",
    title: "Glow input",
    tagline: "Floating label + pastel border glow as one light system.",
    description: "Text input with a floating label that springs on focus and a cursor-mapped pastel border glow. Label and border share the same colour source — they feel like one light system.",
    date: "2026-03-10",
    tech: ["Spring Physics", "requestAnimationFrame", "pastelColour"],
    tags: ["input", "form", "floating-label", "glow", "spring", "cursor"],
    type: "component",
    category: "input",
  },
  {
    slug: "glow-textarea",
    title: "Glow textarea",
    tagline: "Multiline input sharing the glow-input light system.",
    description: "Multiline textarea with a floating label that springs on focus and a cursor-mapped pastel border glow. Same light system as glow-input — resizable, with spring physics on every interaction.",
    date: "2026-03-15",
    tech: ["Spring Physics", "requestAnimationFrame", "pastelColour"],
    tags: ["textarea", "form", "floating-label", "glow", "spring", "cursor", "multiline"],
    type: "component",
    category: "input",
  },
  {
    slug: "floating-dock",
    title: "Floating dock",
    tagline: "macOS-style dock with proximity scaling and glow.",
    description: "macOS-style dock with proximity-based scaling and spring physics. Icons lift and glow with position-mapped pastel colour as your cursor approaches.",
    date: "2026-03-10",
    tech: ["Spring Physics", "Proximity Detection", "pastelColour"],
    tags: ["dock", "navigation", "spring", "proximity", "glow"],
    type: "component",
    category: "navigation",
    featured: true,
  },
  {
    slug: "tilt-card",
    title: "Tilt card",
    tagline: "Perspective tilt with inner highlight tracking the cursor.",
    description: "Card that tilts 2-3 degrees toward your cursor with spring physics. Pastel border glow shifts with pointer position. Subtle inner highlight follows the cursor like a light source.",
    date: "2026-03-15",
    tech: ["Spring Physics", "Perspective Transform", "pastelColour"],
    tags: ["card", "tilt", "perspective", "spring", "3d", "cursor"],
    type: "component",
    category: "layout",
    featured: true,
  },
  {
    slug: "fluid-tooltip",
    title: "Fluid tooltip",
    tagline: "Tooltip that lerps after the cursor with pastel glow.",
    description: "Tooltip that magnetically follows the cursor with lerp delay. Border colour shifts with pointer position via pastelColour. Springs in with opacity and scale on hover.",
    date: "2026-03-15",
    tech: ["Spring Physics", "Lerp Smoothing", "pastelColour"],
    tags: ["tooltip", "cursor", "lerp", "spring", "hover"],
    type: "component",
    category: "feedback",
    featured: true,
  },
  {
    slug: "morph-tabs",
    title: "Morph tabs",
    tagline: "Active pill springs and morphs between tabs.",
    description: "Tab bar where the active indicator springs between tabs. Indicator pill morphs position and width with spring overshoot, coloured by cursor position via pastelColour.",
    date: "2026-03-15",
    tech: ["Spring Physics", "requestAnimationFrame", "pastelColour"],
    tags: ["tabs", "navigation", "spring", "indicator", "morph", "cursor"],
    type: "component",
    category: "navigation",
    featured: true,
  },
  {
    slug: "hover-reveal",
    title: "Hover reveal",
    tagline: "Disclosure that springs in on hover with pastel edge.",
    description: "Content that smoothly reveals on hover with spring physics. Revealed section springs in with opacity, height, and translateY all driven by a damped spring. Pastel border line shifts colour with cursor position.",
    date: "2026-03-15",
    tech: ["Spring Physics", "requestAnimationFrame", "pastelColour"],
    tags: ["hover", "reveal", "spring", "disclosure", "cursor"],
    type: "component",
    category: "disclosure",
  },
  {
    slug: "shimmer-text",
    title: "Shimmer text",
    tagline: "Travelling light band tinted by cursor position.",
    description: "Text with a subtle travelling light band whose colour is mapped to cursor position via pastelColour. The shimmer sweeps across on a loop using rAF with background-clip text.",
    date: "2026-03-15",
    tech: ["requestAnimationFrame", "Background Clip", "pastelColour"],
    tags: ["text", "shimmer", "cursor", "animation", "gradient"],
    type: "component",
    category: "text",
  },
  {
    slug: "glow-badge",
    title: "Glow badge",
    tagline: "Pill badge with breathing pulse and pastel edge.",
    description: "Small pill badge with an organic breathing pulse and cursor-mapped pastel glow border. Variants for success, warning, and error override the colour while keeping the same physics.",
    date: "2026-03-15",
    tech: ["requestAnimationFrame", "Sine Wave", "pastelColour"],
    tags: ["badge", "pill", "pulse", "glow", "cursor", "status"],
    type: "component",
    category: "feedback",
  },
  {
    slug: "pulse-dot",
    title: "Pulse dot",
    tagline: "Notification dot with a breathing expansion ring.",
    description: "Notification dot with an organic breathing pulse ring that expands and fades on a sine wave. Colour follows cursor position unless a fixed colour is provided.",
    date: "2026-03-15",
    tech: ["requestAnimationFrame", "Sine Easing", "pastelColour"],
    tags: ["dot", "notification", "pulse", "cursor", "status"],
    type: "component",
    category: "feedback",
  },
  {
    slug: "spring-toggle",
    title: "Spring toggle",
    tagline: "Switch with spring thumb overshoot and pastel fill.",
    description: "Toggle switch with spring-physics overshoot on the thumb. Track fills with cursor-mapped pastel colour when on. Border glow reacts to cursor proximity.",
    date: "2026-03-15",
    tech: ["Spring Physics", "requestAnimationFrame", "pastelColour"],
    tags: ["toggle", "switch", "spring", "form", "cursor"],
    type: "component",
    category: "input",
  },
  {
    slug: "glow-slider",
    title: "Glow slider",
    tagline: "Range slider with spring bounce and drag bloom.",
    description: "Range slider with spring-physics thumb bounce on grab and release. Fill and border glow with cursor-mapped pastel colour. Drag intensifies the bloom. All motion via rAF springs, no CSS transitions.",
    date: "2026-03-15",
    tech: ["Spring Physics", "requestAnimationFrame", "pastelColour"],
    tags: ["slider", "range", "form", "spring", "glow", "cursor", "drag"],
    type: "component",
    category: "input",
  },
  {
    slug: "avatar",
    title: "Avatar",
    tagline: "Image or initials with proximity-aware pastel ring.",
    description: "Circular avatar with image or fallback initials. Pastel ring glow reacts to cursor proximity, shifting colour with pointer position via pastelColour. All glow via refs and rAF.",
    date: "2026-03-15",
    tech: ["requestAnimationFrame", "Proximity Detection", "pastelColour"],
    tags: ["avatar", "image", "initials", "glow", "cursor", "proximity"],
    type: "component",
    category: "media",
  },
  {
    slug: "progress-bar",
    title: "Progress bar",
    tagline: "Spring-filled bar with travelling shimmer highlight.",
    description: "Track and fill bar with spring-animated width, travelling shimmer highlight, and cursor-proximity pastel glow on the track border. Fill colour shifts with cursor position via pastelColour.",
    date: "2026-03-15",
    tech: ["Spring Physics", "requestAnimationFrame", "pastelColour"],
    tags: ["progress", "bar", "spring", "shimmer", "cursor", "loading"],
    type: "component",
    category: "feedback",
  },
  {
    slug: "skeleton",
    title: "Skeleton",
    tagline: "Loading placeholder with cursor-tinted shimmer.",
    description: "Placeholder loading shape with a cursor-tinted travelling shimmer. A bright band sweeps across on a rAF loop with a hint of pastelColour mapped to cursor position.",
    date: "2026-03-15",
    tech: ["requestAnimationFrame", "Linear Gradient", "pastelColour"],
    tags: ["skeleton", "loading", "placeholder", "shimmer", "cursor"],
    type: "component",
    category: "feedback",
  },
  {
    slug: "icon-button",
    title: "Icon button",
    tagline: "Compact magnetic button with pastel glow.",
    description: "Compact square button with magnetic pull, spring bounce on click, and cursor-mapped pastel glow. Same physics as magnetic-button but smaller radius and weaker strength.",
    date: "2026-03-15",
    tech: ["Spring Physics", "DOM Transforms", "pastelColour"],
    tags: ["button", "icon", "magnetic", "spring", "glow", "cursor"],
    type: "component",
    category: "button",
  },
  {
    slug: "ripple-button",
    title: "Ripple button",
    tagline: "Click-origin pastel ripple tinted by cursor position.",
    description: "Click-origin pastel ripple with cursor-mapped colour and spring physics. Every tap is uniquely tinted by where the pointer lives in the viewport.",
    date: "2026-03-06",
    tech: ["Spring Physics", "requestAnimationFrame", "cursorColour"],
    tags: ["button", "ripple", "spring", "interaction", "click"],
    type: "component",
    category: "button",
    featured: true,
  },
  {
    slug: "command-palette",
    title: "Command palette",
    tagline: "⌘K launcher with fuzzy search, sub-palettes, and a morphing pill highlight.",
    description: "⌘K launcher with fuzzy search, grouped results, sub-palettes, and a morphing highlight pill. Zero external deps — rAF spring entrance, cursor-mapped pastel indicator, colourField scrim behind backdrop blur.",
    date: "2026-04-24",
    tech: ["Spring Physics", "requestAnimationFrame", "Fuzzy Match", "Portal", "pastelColour"],
    tags: ["command", "palette", "search", "launcher", "keyboard", "spring", "cursor", "a11y"],
    type: "component",
    category: "navigation",
    featured: true,
  },

  // --- Playground (visual experiments, not reusable components) ---
  {
    slug: "colour-field",
    title: "Colour field",
    tagline: "Four radial blobs drifting on sine waves.",
    description: "Interactive gradient that shifts with your cursor. Four radial blobs drift on sine waves while colour channels respond to pointer position.",
    date: "2026-03-06",
    tech: ["Canvas", "Pointer Events", "requestAnimationFrame"],
    tags: ["colour", "cursor", "gradient"],
    type: "playground",
    category: "playground",
  },
  {
    slug: "fluid-mesh",
    title: "Fluid mesh",
    tagline: "A grid that deforms like fabric under your cursor.",
    description: "A grid of points connected by lines that deforms like fabric under your cursor. Displacement drives colour intensity. Click for shockwaves.",
    date: "2026-03-06",
    tech: ["Canvas", "Spring Physics", "Mesh Grid"],
    tags: ["mesh", "deformation", "physics"],
    type: "playground",
    category: "playground",
  },
  {
    slug: "text-dissolve",
    title: "Text dissolve",
    tagline: "Pixel-sampled text that shatters on hover.",
    description: "Text rendered as particles that shatter when you hover. Fragments inherit gradient colour as they scatter, then reassemble when you move away.",
    date: "2026-03-06",
    tech: ["Canvas", "Pixel Sampling", "Particle Physics"],
    tags: ["text", "particles", "dissolve"],
    type: "playground",
    category: "playground",
  },
  {
    slug: "gravity-wells",
    title: "Gravity wells",
    tagline: "Click to spawn attractors. Particles spiral into orbit.",
    description: "Click to place gravity attractors. Particles spawn from the edges and spiral into orbits. Trails coloured by velocity. Click a well to remove it.",
    date: "2026-03-06",
    tech: ["Canvas", "Newtonian Gravity", "Particle Systems"],
    tags: ["gravity", "particles", "orbits"],
    type: "playground",
    category: "playground",
  },
  {
    slug: "shader-marbling",
    title: "Shader marbling",
    tagline: "GLSL marble veins that flow toward the cursor.",
    description: "Real-time GLSL marble patterns where the distortion origin follows your mouse. Layered simplex noise creates organic flowing veins. Click for turbulence.",
    date: "2026-03-06",
    tech: ["WebGL", "GLSL", "Simplex Noise"],
    tags: ["shader", "marble", "noise", "webgl"],
    type: "playground",
    category: "playground",
  },
];

export const components = registry.filter((r) => r.type === "component");
export const playground = registry.filter((r) => r.type === "playground");
export const featured = registry.filter((r) => r.featured);

/** Every distinct component category (excludes playground). */
export const componentCategories: Category[] = Array.from(
  new Set(components.map((c) => c.category))
);
